export * from './applications';
export * from './chains';
export * from './community';
export * from './messages';

export const connectChainDarkIcon = require('./connectChain-dark.png');
export const connectChainLightIcon = require('./connectChain-light.png');
export const connectLedgerDarkIcon = require('./connectLedger-dark.png');
export const connectLedgerLightIcon = require('./connectLedger-light.png');
export const connectMnemonicDarkIcon = require('./connectMnemonic-dark.png');
export const connectMnemonicLightIcon = require('./connectMnemonic-light.png');
export const defaultProfileCover = require('./defaultProfileCover.png');
export const defaultProfilePicture = require('./defaultProfilePicture.png');
export const desmosIconGrey = require('./desmosIcon-grey.png');
export const desmosIconOrange = require('./desmosIcon-orange.png');
export const desmosIconWhite = require('./desmosIcon-white.png');
export const desmosLogoOrange = require('./desmosLogo-orange.png');
export const desmosLogoWhite = require('./desmosLogo-white.png');
export const desmosTextOrange = require('./desmosText-orange.png');
export const disconnectIcon = require('./disconnect.png');
export const dsmTokenIcon = require('./dsmToken.png');
export const homeBackgroundDark = require('./homeBackground-dark.png');
export const homeBackgroundLight = require('./homeBackground-light.png');
export const ledgerIcon = require('./ledger.png');
export const noConnectionDarkIcon = require('./noConnection-dark.png');
export const noConnectionLightIcon = require('./noConnection-light.png');
export const noProfileDarkIcon = require('./noProfile-dark.png');
export const noProfileLightIcon = require('./noProfile-light.png');
export const noTransactionDarkIcon = require('./noTransaction-dark.png');
export const noTransactionLightIcon = require('./noTransaction-light.png');
export const resultFailDarkIcon = require('./resultFail-dark.png');
export const resultFailLightIcon = require('./resultFail-light.png');
export const resultPasswordSuccess = require('./resultPasswordSuccess.png');
export const resultRejectDarkIcon = require('./resultReject-dark.png');
export const resultRejectLightIcon = require('./resultReject-light.png');
export const resultSuccessLightIcon = require('./resultSucess-light.png');
export const resultSuccessDarkIcon = require('./resultSucess-dark.png');
export const scanQRButton = require('./scanQRButton.png');
export const splashScreenBackground = require('./splashBackground.png');
export const tickGreyIcon = require('./tick-grey.png');
export const tickOrangeIcon = require('./tick-orange.png');
