export enum Web3AuthLoginProvider {
  Apple = 'apple',
  Discord = 'discord',
  Facebook = 'facebook',
  Github = 'github',
  Google = 'google',
  Kakao = 'kakao',
  Line = 'line',
  Linkedin = 'linkedin',
  Reddit = 'reddit',
  Twitch = 'twitch',
  Twitter = 'twitter',
  Wechat = 'wechat',
  Weibo = 'weibo',
}
