name: Github Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-RC[0-9]+)?'
    branches:
      - manuel/new-version-code-schema

jobs:
  deploy:
    name: Deploying to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup JDK 11 🔧
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK 🔧
        uses: android-actions/setup-android@v2

      - name: Setup ruby 🔧
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock

      - name: Caching Gradle packages 🔨
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Caching ruby dependencies 🔨
        uses: actions/cache@v2
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-gems-${{ secrets.GEMS_CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies 🔨
        run: |
          yarn install
          bundle install

      - name: Build signed apks 🔨
        run: bundle exec fastlane android build_apk
        env:
          VERSION_OVERRIDE: 1.2.0
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          ANDROID_SIGNING_ALIAS: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          PLAYSTORE_JSON_KEY: ${{ secrets.PLAYSTORE_JSON_KEY }}

      - name: Upload binaries to release 🚀
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android/app/build/outputs/apk/release/*.apk
          tag: 1.2.0
          overwrite: true
          file_glob: true
