name: Github Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-RC[0-9]+)?'

jobs:
  github-release:
    name: Release on github
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup Ruby 🔧
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Fix git permissions 🔧
        run: git config --global --add safe.directory /__w/dpm/dpm

      - uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies 🔨
        run: |
          yarn install

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Build signed apks 🔨
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'android build_apk'
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          ANDROID_SIGNING_ALIAS: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          PLAYSTORE_JSON_KEY: ${{ secrets.PLAYSTORE_JSON_KEY }}

      - name: Upload binaries to release 🚀
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android/app/build/outputs/apk/release/*.apk
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
