name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint ✅
        uses: amannn/action-semantic-pull-request@v4.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}